// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/sidebar/Action.vue')['default']
    FilterInput: typeof import('./src/components/FilterInput.vue')['default']
    GameItem: typeof import('./src/components/GameItem.vue')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    RouteBack: typeof import('./src/components/sidebar/RouteBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsSidebar: typeof import('./src/components/settings-sidebar/index.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
    ToggleActions: typeof import('./src/components/sidebar/ToggleActions.vue')['default']
    ToggleMode: typeof import('./src/components/sidebar/ToggleMode.vue')['default']
    ToggleTheme: typeof import('./src/components/sidebar/ToggleTheme.vue')['default']
    ToSettings: typeof import('./src/components/sidebar/ToSettings.vue')['default']
    UserItem: typeof import('./src/components/sidebar/UserItem.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarCollapse: typeof import('@varlet/ui')['_CollapseComponent']
    VarCollapseItem: typeof import('@varlet/ui')['_CollapseItemComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTable: typeof import('@varlet/ui')['_TableComponent']
  }
}
